### ISSUE TITLE
Deliverable 3. Search and discovery integration and APIs

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/folksonomy_engine#4]
```[tasklist]
### Tasks
- [x] Expose API and its documentation (see https://api.folksonomy.openfoodfacts.org/docs )
- [x] #7
- [ ] #8
- [ ] https://github.com/openfoodfacts/folksonomy_frontend/issues/16
- [ ] Eventually, https://github.com/openfoodfacts/folksonomy_frontend/issues/18
```

**Comment by CharlesNepote** [comment]
All of this have been done.
