### ISSUE TITLE
Move Nutri-Score experiment labels to Folksonomy Engine

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/folksonomy_engine#6]
### Description
In 2015, Open Food Facts was used to experiment early versions of the Nutri-Score. To help the experimentation, some products have been labelled "[Nutriscore Experiment](https://world.openfoodfacts.org/label/nutriscore-experiment)". These label were not printed on the product, it was only a convenient way to group these products. Now the experiment is finished, there's no need to use this label anymore. In fact, it is now counterproductive to stay as a label:
* it is confusing with the current Nutri-Score label
* it is proposed automatically by the "suggest as you type" feature when a user wants to add "Nutri-Score" as a label, augmenting the confusion.

All the Nutri-Score Experiment label will be at a better place in Folksonomy Engine. 

### Tasks
- [x] [Write property documentation](https://wiki.openfoodfacts.org/Folksonomy_Engine/Uses_cases#Nutri-Score_experiment)
- [ ] Documentation validation
- [ ] Label all corresponding products with the new properties
- [ ] Delete all old labels
- [ ] Delete the old labels from the taxonomy
